fix: Use parseFloat for sliders, typos
mdn/webaudio-examples pull request #122
Opened 2024-01-25 10:24 UTC by bsmth

Follow-up from https://github.com/mdn/webaudio-examples/pull/113, I think we should be using parseFloat for the rest of the values here. Some typo fixes in parallel

__edit:__

I think this might fix https://github.com/mdn/webaudio-examples/issues/118

2024-01-25 15:36 UTC, ManuLintz requested changes
Thanks for this PR, I'm happy to see that this repo still gets some love :)
I'm working on another PR on the same file so I checked yours.
I just wanted to point out that parseFloat takes only one argument

2024-01-25 15:36 UTC, ManuLintz commented on step-sequencer/index.html
> +          attackTime = parseFloat(ev.target.value, 10);
From what I understand parseFloat takes a single argument:
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/parseFloat
```suggestion
          attackTime = parseFloat(ev.target.value);
```

2024-01-25 15:36 UTC, ManuLintz commented on step-sequencer/index.html
> +          releaseTime = parseFloat(ev.target.value, 10);
same here:
```suggestion
          releaseTime = parseFloat(ev.target.value);
```

2024-01-25 16:17 UTC, bsmth commented on step-sequencer/index.html
> +          attackTime = parseFloat(ev.target.value, 10);
Super, copy paste err - well spotted 👍🏻

2024-01-25 16:57 UTC, ManuLintz approved these changes
I'm approving to let you (and the approving reviewer) know that I'm happy with the changes you made regarding my previous comment

2024-03-20 16:39 UTC, dipikabh approved these changes
LGTM, thank you! 🙌

2024-03-20 16:39 UTC, merged

2024-03-20 16:47 UTC, bsmth commented
Thanks, both!