Add hyperlinks to README
mdn/webaudio-examples pull request #44
Opened 2020-12-02 18:15 UTC by matt-eric

I hyperlinked all Web Audio API references to their respective URLs in the [docs](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API) and made some additional miscellaneous revisions to the description text.

2020-12-03 11:27 UTC, chrisdavidmills requested changes
Thanks @matt-eric , looking mostly good. Just a few nitpicks for you to consider.

2020-12-03 11:27 UTC, chrisdavidmills commented on README.md
> +The [audiocontext-states](https://github.com/mdn/webaudio-examples/tree/master/audiocontext-states) directory contains a simple demo of the new Web Audio API <code>[AudioContext](https://developer.mo
"states property" — put "states" in code font?

2020-12-03 11:27 UTC, chrisdavidmills commented on README.md
> +The [audiocontext-states](https://github.com/mdn/webaudio-examples/tree/master/audiocontext-states) directory contains a simple demo of the new Web Audio API <code>[AudioContext](https://developer.mo
Also put a comma after "<code>resume()</code>"

2020-12-03 11:27 UTC, chrisdavidmills commented on README.md
> +The [spacialization](https://github.com/mdn/webaudio-examples/tree/master/spacialization) directory contains an example of how the various properties of a <code>[PannerNode](https://developer.mozilla
"emulate three-dimensional space" -> "emulate sound in a three-dimensional space" ?

2020-12-04 05:39 UTC, matt-eric commented
Good suggestions, @chrisdavidmills. Thanks for noticing that.

2020-12-04 08:08 UTC, chrisdavidmills approved these changes
Perfect! r+

2020-12-04 08:08 UTC, merged