Prettier part2
mdn/webaudio-examples pull request #90
Opened 2022-10-04 15:56 UTC by bsmth

Same again, slightly larger PR

2022-10-04 15:58 UTC, bsmth commented on create-media-stream-destination/index.html
> +          const blob = new Blob(chunks, { type: "audio/ogg; codecs=opus" });
Must double-check this is correct

2022-10-04 19:16 UTC, dipikabh requested changes

2022-10-04 19:16 UTC, dipikabh commented on spatialization/style.css
> +  border: var(--border);
Indention needed here?

2022-10-04 19:16 UTC, dipikabh commented on spatialization/style.css
> +  cursor: pointer;
indentation required here

2022-10-05 07:42 UTC, bsmth commented on output-timestamp/index.html
> +    <output></output>
Script later on is injecting some content: https://github.com/mdn/webaudio-examples/blob/main/output-timestamp/index.html#L70

2022-10-05 07:51 UTC, bsmth commented on panner-node/style.css
> +  -webkit-transition: 0.1s all;
It looks correct to me:

```css
button {
  background-color: #0088cc;
  background-image: linear-gradient(to bottom, #0088cc 0%, #0055cc 100%);
  text-shadow: 1px 1px 1px black;
  text-align: center;
  color: white;
  border: none;
  width: 120px;
  font-size: 1.5rem;
  line-height: 1.5rem;
  padding: 0.5rem;

  position: absolute;

  box-shadow: inset 0px 0px 0px rgba(0, 0, 0, 0.7);
  transition: 0.1s all;
  -webkit-transition: 0.1s all;
}
```

2022-10-05 08:02 UTC, bsmth commented on create-media-stream-destination/index.html
> +          const blob = new Blob(chunks, { type: "audio/ogg; codecs=opus" });
Works as expected when running locally with `http-server`

2022-10-05 09:46 UTC, bsmth commented on panner-node/style.css
> +button:focus {
Looks fine, tnx

2022-10-05 09:47 UTC, bsmth commented on spatialization/style.css
> +  border: var(--border);
Looks correct 👍🏻

2022-10-05 09:48 UTC, bsmth commented on spatialization/style.css
> +  cursor: pointer;
Looks okay 👍🏻

2022-10-05 09:50 UTC, dipikabh approved these changes
Thank you 👍

2022-10-05 09:50 UTC, merged